POST https://one-favoritephoto-1-be.onrender.com/auth/sign-in
Content-Type: application/json

{
  "email" : "codeit05@codeit.com",
  "password" : "!codeit05"
}

###

GET https://one-favoritephoto-1-be.onrender.com/users/my-cards?grade=-1
Content-Type: application/json

###

GET https://one-favoritephoto-1-be.onrender.com/shop?sort=cheapest