POST https://one-favoritephoto-1-be.onrender.com/auth/sign-in
Content-Type: application/json

{
  "email" : "codeit05@codeit.com",
  "password" : "!codeit05"
}

###

GET https://one-favoritephoto-1-be.onrender.com/users/my-cards/c618558f-f82a-456e-bb98-62084afc7954%7D
Content-Type: application/json

###

GET https://one-favoritephoto-1-be.onrender.com/shop?sort=cheapest